---
- name: Start cockroachdb
  docker_container:
    name: "cockroachdb-{{ inventory_hostname_short }}"
    image: "cockroachdb/cockroach"
    detach: True
    ports: 26257:26257
    command: start --insecure --join="{{ hostvars[groups['cockroachdb-master'][0]]['ansible_' + control_network]['ipv4']['address'] }}" --advertise-host="{{ hostvars[inventory_hostname]['ansible_' + control_network]['ipv4']['address'] }}"
