---
- name: Get docker logs from the ombt agent
  shell: "docker logs {{ item.name  }} > /tmp/ombt-data/{{ item.name }}_docker.log"
  with_items: "{{ ombt_confs }}"
  when: inventory_hostname == item.machine

- name: Fetching docker logs from the ombt agent
  fetch:
    src: "/tmp/ombt-data/{{ item.log }}-controller-{{ inventory_hostname }}.log"
    dest: "{{ backup_dir }}/{{ inventory_hostname }}_{{item.name}}_docker.log"
    flat: yes
  with_items: "{{ ombt_confs }}"
  when: inventory_hostname == item.machine

- name: Fetching omt agent output log
  fetch:
    src: "/tmp/ombt-data/{{ item.log }}"
    dest: "{{ backup_dir }}/{{ inventory_hostname }}_{{item.log}}"
    flat: yes
  with_items: "{{ ombt_confs }}"
  when: inventory_hostname == item.machine
