---
- include: backup/controller.yml
  when: inventory_hostname in groups["ombt-control"]

- include: backup/rpc-server.yml
  when: inventory_hostname in groups["ombt-server"]

- include: backup/rpc-client.yml
  when: inventory_hostname in groups["ombt-client"]
