---
- name: Get docker logs from controller
  shell: "docker logs {{ id }}-ombt-controller > /tmp/ombt-data/{{ id }}-controller-{{ inventory_hostname }}.log"
  when: inventory_hostname in groups['ombt-control']

- name: Fetching controller docker logs
  fetch:
    src: "/tmp/ombt-data/{{ id }}-controller-{{ inventory_hostname }}.log"
    dest: "{{ backup_dir }}/{{ id }}-dockerlog-controller--{{ inventory_hostname }}.log"
    flat: yes
  when: inventory_hostname in groups['ombt-control']

- name: Get docker logs from clients
  shell: "docker logs {{ id }}-ombt-client-{{ item }} > /tmp/ombt-data/{{ id }}-client-{{ inventory_hostname }}-{{ item }}.log"
  when: inventory_hostname in groups['ombt-client']
  with_sequence: count={{ nbr_clients }}

- name: Fetching clients docker logs
  fetch:
    src: "/tmp/ombt-data/{{ id }}-client-{{ inventory_hostname }}-{{ item }}.log"
    dest: "{{ backup_dir }}/{{ id }}-dockerlog-client-{{ inventory_hostname }}-{{ item }}.log"
    flat: yes
  when: inventory_hostname in groups['ombt-client']
  with_sequence: count={{ nbr_clients }}

- name: Fetching clients ombt output
  fetch:
    src: "/tmp/ombt-data/{{ id }}-ombt-client-{{ item }}.log"
    dest: "{{ backup_dir }}/{{ id }}-ombt-client-{{ inventory_hostname }}-{{ item }}.log"
    flat: yes
  when: inventory_hostname in groups['ombt-client']
  with_sequence: count={{ nbr_clients }}

- name: Get docker logs from servers
  shell: "docker logs {{ id }}-ombt-server-{{ item }} > /tmp/ombt-data/{{ id }}-server-{{ inventory_hostname }}-{{ item }}.log"
  when: inventory_hostname in groups['ombt-server']
  with_sequence: count={{ nbr_servers }}

- name: Fetching servers docker logs
  fetch:
    src: "/tmp/ombt-data/{{ id }}-server-{{ inventory_hostname }}-{{ item }}.log"
    dest: "{{ backup_dir }}/{{ id }}-dockerlog-server-{{ inventory_hostname }}-{{ item }}.log"
    flat: yes
  when: inventory_hostname in groups['ombt-server']
  with_sequence: count={{ nbr_servers }}

- name: Fetching servers ombt output
  fetch:
    src: "/tmp/ombt-data/{{ id }}-ombt-server-{{ item }}.log"
    dest: "{{ backup_dir }}/{{ id }}-ombt-server-{{ inventory_hostname }}-{{ item }}.log"
    flat: yes
  when: inventory_hostname in groups['ombt-server']
  with_sequence: count={{ nbr_servers }}


