---
- include: deploy/controller.yml
  when: inventory_hostname in groups["ombt-control"]

- include: deploy/rpc-server.yml
  when: inventory_hostname in groups["ombt-server"]

- include: deploy/rpc-client.yml
  when: inventory_hostname in groups["ombt-client"]
