---
- name: Create ombt-data directory
  file:
    path: "{{ item.log | dirname }}"
    mode: 0777
    state: directory
  with_items: "{{ ombt_confs }}"

- name: Create the client output log file (just in case)
  file:
    path: "{{ item.log }}"
    mode: 0777
    state: touch
  with_items: "{{ ombt_confs }}"
  when: inventory_hostname == item.machine

- name: Start ombt agent
  docker_container:
    image: "{{ ombt_version }}"
    command: "{{ item.command }}"
    name: "{{ item.name }}"
    detach: "{{ item.detach }}"
    network_mode: host
    state: started
    volumes:
      - "{{ item.log }}:{{item.docker_log}}"
  when: inventory_hostname == item.machine
  with_items: "{{ ombt_confs }}"
