---
- name: Create ombt-data directory
  file:
    path: /tmp/ombt-data
    mode: 0777
    state: directory

- name: Create the client output log file (just in case)
  file:
    path: "/tmp/ombt-data/{{ item.log }}"
    mode: 0777
    state: touch
  with_items: "{{ ombt_confs }}"
  when: inventory_hostname == item.machine

- name: Start ombt agent
  docker_container:
    image: "beyondtheclouds/ombt:{{ ombt_version }}"
    command: "{{ item.command }}"
    name: "{{ item.name }}"
    detach: True
    network_mode: host
    state: started
    volumes:
      - "/tmp/ombt-data/{{ item.log }}:{{agent_log}}"
  when: inventory_hostname == item.machine
  with_items: "{{ ombt_confs }}"
