---
- name: Common configuration
  hosts: all
  roles:
    - common
    - registry
    - telegraf

- name: Deploy prometheus
  hosts: prometheus
  roles:
    - prometheus

- name: Deploy the grafana
  hosts: grafana
  roles:
    - grafana
