---
- name: Installing dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python-setuptools
    # - git
    # - gcc
    # - python-dev

- easy_install:
    name: pip
    state: latest

- name: Install some python bindings
  pip:
    name: "{{ item }}"
  with_items:
    - docker
    - influxdb

- name: Mount /run
  command: mount --make-shared /run
