---
- name: Create the configuration directory
  file:
    path: /etc/qpid-generator
    state: directory

- name: Generate the configuration files
  template:
    src: qdrouterd.conf.jinja2
    dest: "/etc/qpid-generator/{{ item.router_id }}.conf"
  with_items: "{{ qpidd_confs }}"
  when: item.machine == inventory_hostname

- name: Start qdrouterd(s)
  docker_container:
    image: msimonin/qdrouterd
    name: "{{ item.router_id }}"
    volumes:
      - "/etc/qpid-generator/{{ item.router_id }}.conf:/etc/qpid-dispatch/qdrouterd.conf"
    network_mode: host
    state: started
  with_items: "{{ qpidd_confs }}"
  when: item.machine == inventory_hostname

#
# Start the gui
#
- name: Start the web gui
  docker_container:
    image: msimonin/qpid-dispatch-gui
    name: qpid-dispatch-gui
    network_mode: host
    state: started
  when: inventory_hostname == groups['router'][0]

#
# Websockify AMQP listener
#
- name: Websockify AMQP listener
  docker_container:
    image: msimonin/websockify
    command: "0.0.0.0:4999 {{ hostvars[inventory_hostname]['ansible_' + control_network]['ipv4']['address'] }}:5000"
    name: websockify
    network_mode: host
    state: started
  when: inventory_hostname == groups['router'][0]
