---
- name: Start ombt rpc-client
  docker_container:
    image: "{{ ombt_version }}"
    command: "{{ item.command }}"
    name: "{{ item.name }}"
    detach: "{{ item.detach }}"
    network_mode: host
    state: started
  when: inventory_hostname == item.machine
  with_items: "{{ ombt_confs['rpc-client'] }}"
