---
- name: Install collectd agent
  apt: name=collectd state=present

- name: Install the influxdb connector
  template: src=influx.conf.j2 dest=/etc/collectd/collectd.conf.d/influx.conf

- name: Install the configuration file
  copy: src=collectd.conf dest=/etc/collectd/

- name: Install the protocols plugin
  copy: src=protocols.conf dest=/etc/collectd/collectd.conf.d/

- name: Restart collectd
  service:
    name: collectd
    state: restarted

