---
- name: Configuring prometheus
  template:
    src: prometheus.yml.j2
    dest: /prometheus.yml

- name: Create data directory
  file:
    path: /prometheus-data
    mode: 0777
    state: directory

- name: Install prometheus container
  docker_container:
    name: "prometheus"
    image: "prom/prometheus"
    detach: True
    ports:
      - "9090:9090"
    state: started
    volumes:
      - "/prometheus-data:/prometheus"
      - "/prometheus.yml:/etc/prometheus/prometheus.yml:ro"

