---
- name: Create the directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ["/opt/local/etc/mysql.conf.d/", "/mnt/data"]

- name: Generate the configuration file
  template:
    src: mariadb-master.conf.j2
    dest: /opt/local/etc/mysql.conf.d/mysql_server.cnf
  with_list: "{{ [groups['all']] }}"

- name: Start the MariaDB-master container
  docker_container:
    name: "mariadb-master"
    image: "mariadb"
    detach: True
    exposed_ports:
      - 4567
    published_ports:
      - "3306:3306"
      - "4567:4567"
      - "4567:4567/udp"
      - "4568:4568"
      - "4444:4444"
    volumes:
      - "/opt/local/etc/mysql.conf.d:/etc/mysql/conf.d"
      - "/mnt/data:/var/lib/mysql"
    env:
      MYSQL_INITDB_SKIP_TZINFO=yes
      MYSQL_ROOT_PASSWORD=my-secret-pw
    command: --wsrep-new-cluster --wsrep_node_address="{{ hostvars[inventory_hostname]['ansible_' + control_network]['ipv4']['address'] }}"
